Payroll/Controllers/AttendanceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Payroll.Application.Services.ServiceImplementation;
using Payroll.Application.Services.ServiceInterface;
using System.Security.Claims;

namespace Payroll.Web.Controllers
{
    public class AttendanceController : Controller
    {
        private readonly IAttendenceService attendenceService;
        private readonly IEmployeeService employeeService;

        public AttendanceController(IAttendenceService attendenceService,IEmployeeService employeeService)
        {
            this.attendenceService = attendenceService;
            this.employeeService = employeeService;
        }
        [Authorize(Roles ="HR")]
        public async Task<IActionResult> Index()
        {
            var AttendanceList = await attendenceService.getAttendenceList();
            return View(AttendanceList);
        }
        [Authorize(Roles = "Employee")]
        public async Task<IActionResult> GetPunchInOutStatus(int employeeId)
        {
            var latestAttendance = await attendenceService.getLatest(employeeId); 
            return PartialView("_PunchInOut", latestAttendance);
        }
        [HttpPost]
        [Authorize(Roles = "Employee")]
        public async Task<IActionResult> PunchIn()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int id = employeeService.getEmpId(userId);
            await attendenceService.PunchIn(id);
            return Redirect(Request.Headers["Referer"].ToString());
        }

        [HttpPost]
        [Authorize(Roles = " Employee")]
        public async Task<IActionResult> PunchOut()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int id = employeeService.getEmpId(userId);
            await attendenceService.PunchOut(id);
            return Redirect(Request.Headers["Referer"].ToString());
        }
        [HttpGet]
        public async Task<IActionResult> getTotalWorkingHours(int EmpId)
        {
            var totalWorkingHours = await attendenceService.getTotalWorkingHours(EmpId);
            var hours = totalWorkingHours.Hours;
            var minutes = totalWorkingHours.Minutes;
            return Json(new { hours, minutes });
        }



    }
}

Payroll/Controllers/BankController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Payroll.Application.Services.ServiceInterface;
using Payroll.Domain.Entities;
namespace Payroll.Web.Controllers
{
    public class BankController : Controller
    {
        private readonly IBankDetailsService bankDetailsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IEmployeeService employeeService;

        public BankController(IBankDetailsService bankDetailsService,UserManager<ApplicationUser> userManager,IEmployeeService employeeService)
        {
            this.bankDetailsService = bankDetailsService;
            this.userManager = userManager;
            this.employeeService = employeeService;
        }
        [Authorize(Roles ="Admin,HR")]
        public async Task<IActionResult> Index()
        {
            var bankList = await bankDetailsService.GetBankList();
            return View(bankList);
        }
        public async Task<IActionResult> Details(int id)
        {
            var user = await userManager.GetUserAsync(User);
            var bankDetails = await bankDetailsService.GetById(id);
            bankDetails.AccountHolderName = user.FirstName + user.LastName;
            return View(bankDetails);
        }
        [Authorize(Roles ="Employee")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(BankDetails bankDetails)
        {

            var user=await userManager.GetUserAsync(User);
            bankDetails.EmployeeId = employeeService.getEmpId(user.Id);
            bankDetails.AccountHolderName = employeeService.getName(user.Id);
            if (ModelState.IsValid)
            { 
                await bankDetailsService.Create(bankDetails);
                return RedirectToAction("Index");
            }
            return View(bankDetails);
        }
        public  async Task<IActionResult> Edit(int id)
        {
            var bank = await bankDetailsService.GetById(id);

            return View(bank);

        }
        [HttpPost]
        public async Task<IActionResult> Edit(BankDetails bank)
        {
            var bankDetails = await bankDetailsService.GetById(bank.Id);
            if(bankDetails == null)
            {
                return NotFound();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    await bankDetailsService.Update(bankDetails);
                    return RedirectToAction("Index");
                }
            }
            return View(bankDetails);   
        }
        public async Task<IActionResult> Delete(int id)
        {
            var bank = await bankDetailsService.GetById(id);
            if (bank != null)
            {
                await bankDetailsService.Delete(id);
                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }
         
        }
    }
}

Payroll/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;

using Payroll.Application.Services.ServiceInterface;
using Payroll.Domain.Entities;

namespace Payroll.Web.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            this.departmentService = departmentService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await departmentService.GetDepartments());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Department department)
        {
            if (ModelState.IsValid)
            {
                await departmentService.Create(department);
                return RedirectToAction("Index");
            }
            return View(department);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var dep = await departmentService.GetById(id);
            if (dep != null)
            {
                return View(dep);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Department department)
        {
            if (ModelState.IsValid)
            {
                await departmentService.Update(department);
                return RedirectToAction("Index");
            }
            return View(department);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var dep = await departmentService.GetById(id);
            if (dep != null)
            {
                await departmentService.Delete(dep.DepartmentId);
                return RedirectToAction("Index");
            }
            return NotFound();
        }
        public IActionResult EmployeeList(int id)
        {
            var empList = departmentService.getEmployeeInDepartment(id);
            return View(empList);
        }
    }
}

Payroll/Controllers/SalaryController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using Payroll.Application.Services.ServiceInterface;
using Payroll.Domain.Entities;


namespace Payroll.Web.Controllers
{
    public class SalaryController : Controller
    {
        private readonly ISalaryService salaryService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IEmployeeService employeeService;

        public SalaryController(ISalaryService salaryService,UserManager<ApplicationUser> userManager,IEmployeeService employeeService)
        {
            this.salaryService = salaryService;
            this.userManager = userManager;
            this.employeeService = employeeService;
        }
        public IActionResult Index()
        {
            var salList= salaryService.GetAll();
            return View(salList);
        }
        public async Task<IActionResult> Create()
        {
            var employees = await employeeService.GetEmployees();

            ViewBag.Employees = employees.Select(e => new
            {
                Id = e.Id,
                Name = e.ApplicationUser.FirstName + " " + e.ApplicationUser.LastName
            }).ToList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Salary salary)
        {
            var employees = await employeeService.GetEmployees();
            ViewBag.Employees = employees.Select(e => new
            {
                Id = e.Id,
                Name = e.ApplicationUser.FirstName + " " + e.ApplicationUser.LastName
            }).ToList();
            salary.PaymentDate = DateTime.Now;            
            if (ModelState.IsValid)
            {
              await  salaryService.Create(salary);
                return RedirectToAction("Index");
            }
            return View(salary);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var employees = await employeeService.GetEmployees();
            ViewBag.Employees = employees.Select(e => new
            {
                Id = e.Id,
                Name = e.ApplicationUser.FirstName + " " + e.ApplicationUser.LastName
            }).ToList();
            var sal = await salaryService.GetById(id);
            return View(sal);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Salary salary)
        {
            var employees = await employeeService.GetEmployees();
            ViewBag.Employees = employees.Select(e => new
            {
                Id = e.Id,
                Name = e.ApplicationUser.FirstName + " " + e.ApplicationUser.LastName
            }).ToList();
            if (ModelState.IsValid)
            {
               salary.PaymentDate=DateTime.Now; 
                await salaryService.Update(salary);
                return RedirectToAction("Index");
            }
            else
            {
                return View(salary);
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            var sal=await salaryService.GetById(id);
            if (sal == null)
            {
                return NotFound();
            }
            else
            {
               await salaryService.Delete(id);
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> Details(int id)
        {
            var sal=await salaryService.GetById(id);
            if (sal == null)
            {
                return NotFound();
            }
            else
            {
                return View(sal);
            }
           
        }
    }
}

Payroll/Views/Shared/_Layout.cshtml
@inject IEmployeeService employeeService
@inject IAttendenceService attendanceService
@using System.Security.Claims
@using Payroll.Application.Services.ServiceImplementation
@using Payroll.Application.Services.ServiceInterface

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Payroll Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/24.2.3/css/dx.material.blue.light.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn3.devexpress.com/jslib/24.2.3/js/dx.all.js" defer></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary shadow-sm">
            <div class="container">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Payroll Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        @if (User.IsInRole("Admin") || User.IsInRole("HR"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Employee" asp-action="Index">Employees</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Department" asp-action="Index">Departments</a>
                            </li>
                            @if (User.IsInRole("HR"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-controller="Salary" asp-action="Index">Salary</a>
                                </li>
                            }
                        }
                        @if (User.IsInRole("Employee"))
                        {
                            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                            int id = employeeService.getEmpId(userId);
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Employee" asp-action="Details" asp-route-id="@id">Personal Details</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Bank" asp-action="Create">Bank Details</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Salary" asp-action="Details" asp-route-id="@id">Salary</a>
                            </li>
                        }
                    </ul>
                    @if (User.IsInRole("Employee"))
                    {
                        string userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                        int empId = employeeService.getEmpId(userid);
                        var attendance = await attendanceService.getLatest(empId);
                        <partial name="_PunchInOut" model="attendance" />
                    }
                    <partial name="_LoginPartial" />
                  
                </div>
            </div>
        </nav>
    </header>

    <div class="container mt-4">
       
        <main role="main" class="py-4">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-light text-center py-3 mt-5 shadow-sm">
        <div class="container">
            &copy; 2025 - Payroll Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

 
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Payroll/Views/Shared/_PunchInOut.cshtml
@using Payroll.Application.Services.ServiceInterface
@using System.Security.Claims

@inject IEmployeeService employeeService
@inject IAttendenceService attendenceService 
@model Payroll.Domain.Entities.Attendence

<ul class="navbar-nav">
    @if (User.IsInRole("Employee"))
    {
        string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        int id = employeeService.getEmpId(userId);

        <li class="nav-item">
            @if (Model == null || Model.inTime == null)
            {
                <form asp-controller="Attendance" asp-action="PunchIn" asp-route-id="@id" method="post">
                    <button type="submit" class="btn btn-success">Punch In</button>
                </form>
            }
            else if (Model.outTime == null)
            {
                <form asp-controller="Attendance" asp-action="PunchOut" asp-route-id="@id" method="post">
                    <button id="PunchOut" type="submit" class="btn btn-danger" onclick="showTotalWorkingHours(@id)">Punch Out</button>
                </form>
            }
        </li>
    }
</ul>
<script>

    function showTotalWorkingHours(empId) {
      
        $.ajax({
            url: '/Attendance/getTotalWorkingHours', 
            type: 'GET',
            data: { empId: empId },
            success: function (data) {
                if (data.hours !== undefined && data.minutes !== undefined) {
                    alert(`You have worked for: ${data.hours} hours and ${data.minutes} minutes.`);
                } else {
                    alert('Error fetching total working hours.');
                }
            },
            error: function () {
                alert('An error occurred while fetching total working hours.');
            }
        });
    }
</script>